name: GitGoogleContainer
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      - name: Login in Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ACCESS_TOKEN }}
      - name: Docker pull and push
        run: |
          docker pull docker.io/calico/cni:v3.22.2
          docker tag  docker.io/calico/cni:v3.22.2 ghcr.io/asvex/calico/cni:v3.22.2
          docker pull docker.io/calico/node:v3.22.2
          docker tag  docker.io/calico/node:v3.22.2 ghcr.io/asvex/calico/node:v3.22.2
          docker pull docker.io/coredns/coredns:1.8.7
          docker tag  docker.io/coredns/coredns:1.8.7 ghcr.io/asvex/coredns/coredns:1.8.7
          docker pull docker.io/calico/kube-controllers:v3.22.2
          docker tag  docker.io/calico/kube-controllers:v3.22.2 ghcr.io/asvex/calico/kube-controllers:v3.22.2
          docker pull docker.io/calico/pod2daemon-flexvol:v3.22.2
          docker tag  docker.io/calico/pod2daemon-flexvol:v3.22.2 ghcr.io/asvex/calico/pod2daemon-flexvol:v3.22.2  
          docker push ghcr.io/asvex/calico/cni:v3.22.2
          docker push ghcr.io/asvex/calico/node:v3.22.2
          docker push ghcr.io/asvex/coredns/coredns:1.8.7
          docker push ghcr.io/asvex/calico/kube-controllers:v3.22.2
          docker push ghcr.io/asvex/calico/pod2daemon-flexvol:v3.22.2
